name: "davidkhala/setup-podman"
description: "Setup Podman context"

branding:
  icon: "package"
  color: "purple"

runs:
  using: "composite"
  steps:
    - if: runner.os == 'Linux'
      run: |
        curl -sS https://raw.githubusercontent.com/davidkhala/setup-podman/refs/heads/main/ubuntu/setup.sh | bash
        podman machine init --user-mode-networking --now
      shell: bash
    - if: runner.os == 'Windows'
      run: |
        iex (iwr 'https://raw.githubusercontent.com/davidkhala/setup-podman/refs/heads/main/windows/setup.ps1').Content
        'C:\Program Files\RedHat\Podman' | Out-File -FilePath $env:GITHUB_PATH -Append
      shell: powershell
