#!/bin/bash
# Save as /usr/bin/qemu-system-x86_64

args=()
skip_next=false
for arg in "$@"; do
  if $skip_next; then skip_next=false; continue; fi
  case "$arg" in
    -accel|-cpu) skip_next=true ;;
    -accel=*|-cpu=*) ;;
    *) args+=("$arg") ;;
  esac
done

exec /usr/bin/qemu-system-x86_64.real -accel tcg -cpu max -display none "${args[@]}"
