name: self reference
on: push
jobs:
    use:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
        - uses: actions/checkout@main
        - uses: ./
        - run: podman context ls
        - if: runner.os == 'Linux'
          run: ls /opt/cni/bin # validate network plugins are installed
        - if: runner.os == 'Windows'
          run:  podman image pull postgres
        
    
