name: self reference
on: push
jobs:
    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@main
        - uses: ./
        - run: podman context ls
        - run: podman image pull postgres
    ubuntu:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                socket: [systemctl, podman-machine]
        steps:
        - uses: actions/checkout@main
        - uses: ./
          with:
            socket: ${{ matrix.socket }}
        - run: podman image pull postgres
        - run: ls /opt/cni/bin # validate network plugins are installed
            
    
